services:
  - type: web
    name: surabank
    env: node
    plan: free
    region: oregon
    buildCommand: npm install --include=dev && npx prisma generate && npx prisma db push && npm run db:seed && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
